### ISSUE TITLE
Goblins spawn is weird

### ISSUE THREAD

**Issue by RealxRancor** [NickSuttonDicken/FantasyOrigins#2]
those pesky lil grumps :D,
the spawn of thos creatures are weird they are falling from the sky outta nowhere and in weird quantity
can u cap that and maybe balance that my server ppl are kinda annoyed

**Comment by Revan7even** [comment]
![javaw_2022_03_27_20_07_40_053](https://user-images.githubusercontent.com/60712998/160958256-19bd7a41-0935-4835-abb6-06b774d7e159.jpg)
This is every night. They sometimes spawn even in areas lit by torches where vanilla mobs don't spawn might be their size or the insane rate). They spawn in high quantities, spawn frequently, and they have spawned so many in caves underground that the server OP has to run kill commands to clear out mobs becasue they're lagging the server.

EntityInit has `BiomeModifications.addSpawn(goblinSpawnKeys, spawnGroup, GOBLIN, 8, 2, 4);`, which if I'm understanding right the 8 is weight and it's less than endermen's 10, while zombies and skeletons have a weight of 100, so the Goblins _should_ be spawning less often than endermen, as everything else has a higher weight and is given higher priority to spawn.

**Comment by Revan7even** [comment]
![image](https://user-images.githubusercontent.com/60712998/161876726-86657efc-ad44-4628-909b-e2ef6c01ea17.png)

Not kidding about the cave spawn rate. This is a cave 100 blocks below the village where I've built (night vision on, it's not lit in the pic). The server OP had to go into spectator mode to find it, and as soon as he ran the kill command everyone's problem on the server with mobs "lagging" becasue they were only updating once a second was fixed.

I spent all day digging a tower down to it and cleaning it up. Got almost 8 stacks of porkchops before I lit the cave up enough to curb the spawns (there's an upper level I haven't reached), and my Goblin kill count went up by at least 250.

**Comment by NickSuttonDicken** [comment]
Sorry for taking so long to respond.
Do you have any other mods installed?

**Comment by Revan7even** [comment]
> Sorry for taking so long to respond. Do you have any other mods installed?

Can't speak for RealxRancor, but our server has Better End, Better Nether, Terralith, Origins, Extra Origins, Fantasy Origins, Origins Classes, and Attribute fix, in addition to all the libraries and APIs required by/bundled in them.

I'm not the server owner so I can't change these. Closest thing that could be influencing it (though it shouldn't be to the point of having 50 mobs on screen) is Terralith, since its biomes don't seem to add any spawns, vanilla or modded, forcing spawns to be clustered in vanilla biomes. However that doesn't explain how Goblins have a lower spawn weight than Endermen yet spawn 10x more than Zombies, Skeletons, Spiders, and Creepers. If Terralith is causing an increase in spawn density, Goblins must have something going on beforehand or there would be more vanilla mob spawns, and vanilla mob spawns appear the same density and rate as an unmodded world.

**Comment by RealxRancor** [comment]
> Sorry for taking so long to respond. Do you have any other mods installed?

I have made big modpack but still there is no reason for Stuff Happening like that

**Comment by OfficialLahusa** [comment]
I can confirm this issue. The SMP server I host is running FantasyOrigins as part of a small modpack and the goblins seem to spawn in midair even in well lit buildings, aswell as in huge quantities.
